CREATE TABLE IF NOT EXISTS events (
  pk INT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(191) UNIQUE,
  slug VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100),
  shortDescription TEXT,
  description TEXT,
  image VARCHAR(500),
  date VARCHAR(20),
  startTime VARCHAR(20),
  endTime VARCHAR(20),
  timezone VARCHAR(50),
  mode VARCHAR(20),
  venue VARCHAR(255),
  address VARCHAR(500),
  city VARCHAR(100),
  googleMeetLink VARCHAR(500),
  meetingLink VARCHAR(500),
  organizer VARCHAR(255),
  speaker VARCHAR(255),
  registrationOpen BOOLEAN DEFAULT TRUE,
  capacity INT,
  availableSeats INT,
  priceType VARCHAR(20),
  price VARCHAR(50),
  razorpayLink VARCHAR(500),
  paymentLink VARCHAR(500),
  status VARCHAR(20) DEFAULT 'published',
  featured BOOLEAN DEFAULT FALSE,
  seo JSON,
  createdAt DATETIME,
  updatedAt DATETIME,
  publishedAt DATETIME NULL
);

CREATE TABLE IF NOT EXISTS blogs (
  pk INT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(191) UNIQUE,
  slug VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  excerpt TEXT,
  content LONGTEXT,
  category VARCHAR(100),
  image VARCHAR(500),
  author VARCHAR(255),
  status VARCHAR(20) DEFAULT 'published',
  readTime VARCHAR(50),
  details JSON,
  seo JSON,
  createdAt DATETIME,
  updatedAt DATETIME,
  publishedAt DATETIME NULL
);

CREATE TABLE IF NOT EXISTS orders (
  pk INT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(191) UNIQUE,
  customerName VARCHAR(255),
  phone VARCHAR(50),
  email VARCHAR(255),
  address VARCHAR(500),
  city VARCHAR(100),
  state VARCHAR(100),
  zipcode VARCHAR(20),
  country VARCHAR(100),
  items JSON,
  subtotal DECIMAL(10,2) DEFAULT 0,
  shipping DECIMAL(10,2) DEFAULT 0,
  discount DECIMAL(10,2) DEFAULT 0,
  totalAmount DECIMAL(10,2) DEFAULT 0,
  paymentMethod VARCHAR(20),
  paymentStatus VARCHAR(20),
  status VARCHAR(20) DEFAULT 'New',
  internalNotes TEXT,
  createdAt DATETIME,
  updatedAt DATETIME
);

CREATE TABLE IF NOT EXISTS enrollments (
  pk INT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(191) UNIQUE,
  fullName VARCHAR(255),
  phone VARCHAR(50),
  email VARCHAR(255),
  city VARCHAR(100),
  interest VARCHAR(255),
  type VARCHAR(50),
  sourceType VARCHAR(50),
  eventId VARCHAR(191),
  eventTitle VARCHAR(255),
  message TEXT,
  status VARCHAR(20) DEFAULT 'New',
  internalNotes TEXT,
  submittedAt DATETIME,
  updatedAt DATETIME
);

CREATE TABLE IF NOT EXISTS messages (
  pk INT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(191) UNIQUE,
  name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(50),
  subject VARCHAR(255),
  message TEXT,
  status VARCHAR(20) DEFAULT 'New',
  submittedAt DATETIME
);
